language: python
python:
- "3.6"

#install:
#- git clone "https://oauth2:$Gitlab_token@repo.theloop.co.kr/icon/icon-sdk/icon-sdk-java-test.git"
#- cd icon-sdk-java-test
#- npm install
#- node index.js &
#- cd ..

#script:
#- python setup.py test

deploy:
  provider: testpypi
  distributions: sdist bdist_wheel
  on:
    branch: master
    user: iconfoundation
    password: $Pypi_pw
