language: python
 jobs:
  include:
    before_install:
      - virtualenv venv
      - . venv/bin/activate
    install:
      - pip3 install -r requirements.txt
      - git clone https://repo.theloop.co.kr/icon/icon-sdk/icon-sdk-java-test.git
      - cd icon-sdk-java-test
      - npm install
      - node index.js
      - cd ..
    script:
      - python3 setup.py test
    deploy:
      provider: testpypi
      distributions: sdist bdist_wheel
      on:
        branch: master
        user: iconfoundation
        password: