language: python
python:
- "3.6"

install:
- git clone "https://oauth2:$Gitlab_token@repo.theloop.co.kr/icon/icon-sdk/icon-sdk-java-test.git"
- cd icon-sdk-java-test
- npm install
- node index.js &
- cd ..
- rm -rf icon-sdk-java-test

script:
- echo "123"

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  server: https://testpypi.python.org/pypi
  user: iconfoundation
  password: $Pypi_pw
  on:
    branch: master
