language: python
python:
  - "3.6"
  - "3.7"

jobs:
 include:
  before_install:
   - virtualenv venv
   - . venv/bin/activate
  install:
   - pip install -r requirements.txt
   - python3 setup.py test

