language: python
python:
  - "3.6"
virtualenv:
  system_site_packages: true
jobs:
 include:
  install:
   - pip install -r requirements.txt
   - git clone https://repo.theloop.co.kr/icon/icon-sdk/icon-sdk-java-test.git
   - cd icon-sdk-java-test
   - npm install
   - node index.js
   - cd ..
  script:
   - python setup.py test
