language: python
python:
  - "3.6"
  - "3.7"

jobs:
 include:
  before_install:
   - virtualenv venv
   - . venv/bin/activate
  install:
   - pip install -r requirements.txt
   - python3 setup.py test
  deploy:
    provider: testpypi
    distributions: sdist bdist_wheel
    on:
     branch: master
     user: iconfoundation
     password:
